---
- name: Install and configure Nginx
  hosts: vm_nginx
  become: yes
  vars:
    user: "ocop"

  tasks:
    - name: Add user to group root
      user:
        name: "{{ user }}"
        groups: root
        state: present

    - name: Archive source
      archive:
        path: ./build/
        dest: ./docusaurus.tar.gz
      delegate_to: localhost

    - name: Create target directory
      file:
        path: /var/www/ocopee/docusaurus
        state: directory

    - name: Extract to source
      ansible.builtin.unarchive:
        src: ./docusaurus.tar.gz
        dest: /var/www/ocopee/docusaurus

    - name: Restart nginx to reload
      service: name=nginx state=restarted

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
